### ISSUE TITLE
mguxdemo get_image_type: unknown type jpg

### ISSUE THREAD

**Issue by nicetake** [VincentWei/build-minigui-3.2#3]
run ./mguxdemo

load res/pictureviewer/picplayer/pic_prev.png
end load resource.(107)
LoadAllRes: 107
NCSActivity 35
ScreenLockActivity::loadMyResource called
Activity::create called!
ScreenLockActivity onCreate
created window by createHWND: 0x1bce5b0!
>>>>>>>> push activity: ScreenLockActivity 0x1ab0300
get_image_type: unknown type jpg.
已放弃 (核心已转储)

**Comment by VincentWei** [comment]
Obliviously, you did not install jpeglib-dev package to your system!

Please read http://www.minigui.com/blog/minigui-3.2.0-released/ carefully.
