### ISSUE TITLE
 build mg-samples

### ISSUE THREAD

**Issue by htk719809837** [VincentWei/build-minigui-3.2#7]
Hello, when I tried to build MiniGUI samples, the following problems occurred. The version of MiniGUI is 3.2.3
make[2]: Entering directory '/home/huang/Downloads/minigui/mg-samples-3.2.2/mginit'
gcc -DPACKAGE_NAME=\"mg-samples\" -DPACKAGE_TARNAME=\"mg-samples\" -DPACKAGE_VERSION=\"3.2.2\" -DPACKAGE_STRING=\"mg-samples\ 3.2.2\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"mg-samples\" -DVERSION=\"3.2.2\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DSTDC_HEADERS=1 -DHAVE_SYS_WAIT_H=1 -DTIME_WITH_SYS_TIME=1 -DHAVE_SYS_TIME_H=1 -DHAVE_UNISTD_H=1 -D_LANG_EN=1 -DHAVE_DECL__MGRM_PROCESSES=1 -I.     -g -O2 -Wstrict-prototypes -pipe -MT taskbar.o -MD -MP -MF .deps/taskbar.Tpo -c -o taskbar.o taskbar.c
In file included from taskbar.c:20:0:
/usr/local/include/minigui/ctrl/coolbar.h:105:5: error: unknown type name ‘PBITMAP’
     PBITMAP Bmp;
     ^
/usr/local/include/minigui/ctrl/coolbar.h:118:5: error: unknown type name ‘DWORD’
     DWORD dwAddData;
     ^
taskbar.c: In function ‘create_app_coolbar’:
taskbar.c:152:18: warning: assignment makes integer from pointer without a cast [enabled by default]
     bar_item.Bmp = NULL;
                  ^
taskbar.c:164:22: warning: assignment makes integer from pointer without a cast [enabled by default]
         bar_item.Bmp = &app_item->bmp;
                      ^
Makefile:403: recipe for target 'taskbar.o' failed
make[2]: *** [taskbar.o] Error 1
make[2]: Leaving directory '/home/huang/Downloads/minigui/mg-samples-3.2.2/mginit'
Makefile:436: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/home/huang/Downloads/minigui/mg-samples-3.2.2/mginit'
Makefile:389: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

**Comment by htk719809837** [comment]
i have solved it , add two header files to /libminigui-3.2.3/include/ctrl/coolbar.h   
 #include <minigui/gdi.h>
#include <minigui/common.h>

**Comment by VincentWei** [comment]
Although there are different ways to handle the dependencies of C headers, I suggest that you include the MiniGUI headers in you **application source files** in the recommended order:

```c
#include <minigui/common.h>
#include <minigui/minigui.h>
#include <minigui/gdi.h>
#include <minigui/window.h>
#include <minigui/control.h>   // include only if it is needed

...
```

**Comment by htk719809837** [comment]
> 尽管有不同的方法来处理 C 头文件的依赖关系，但我建议您按照推荐的顺序在**应用程序源文件中包含 MiniGUI 头文件：**
> 
> ```c
> #include < minigui/common.h > #include  < minigui/minigui.h > 
> #include < minigui/gdi.h > #include < minigui / window.h 
> > #include 
> < minigui 
> / control.h > //仅当这是必需的       
> 
> ...
> ```

thanks
